## 6장 소프트맥스 분류

In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.0.0-alpha0


In [2]:
tf.random.set_seed(100) # 반복실행 시 값 고정

* Logistic Regression이 이진분류(Binary Classfication)이라면
* Softmax Regression은 다진분류(Multinomial Classification)의 과정
* A or not, B or not, C or not의 방식으로 Hypothesis를 찾는다.

<img width  = 100% src = "https://i.postimg.cc/RV5Hbqsb/image1.png">

* 매번 식을 통해서 하기보다 Matrix 형태를 통해 다진 분류의 과정을 진행한다.
* 그리고 이렇게 나온 Hypothesis를 logistic regression에 넣어 A or not, B or not, C or not의 과정으로 이진 분류를 각각 해준다.

<img width  = 100% src = "https://i.postimg.cc/L62s1P0R/image2.png">

* 그런데 이렇게 나온 score를 단순히 쓰는 게 아니라 '어떠한' 과정을 통해 해당 값의 확률로 전환한다.

<img width  = 100% src = "https://i.postimg.cc/RCQS4FCY/image3.png">

* '어떠한' 방법이란 S(y), 즉 '소프트맥스 함수'
* 1. 각 값을 0 ~ 1 사이의 값으로
* 2. 전체를 더하면 1의 상태로 파악
* 3. 즉 결과값을 '확률'로 볼 수 있음

<img width  = 100% src = "https://i.postimg.cc/jjPVcgL1/image6.png">

* 1. 그렇게 나온 확률에 기반한 Y값은
* 2. 원-핫 인코딩을 통해 그 중 하나의 값만 정하고 나머지를 없애도록 한다. (argmax 사용)

<img width  = 100% src = "https://i.postimg.cc/V6Pwcyx1/image4.png">

* 1. 그렇게 확보한 Softmax값과 실제값을 '크로스 엔트로피(Cross Entropy)'의 과정을 통해 Cost Function을 구함
* 2. 앗...아니 왜 기껏 구한 Si값에 log를 씌우냐고?

<img width  = 100% src = "https://i.postimg.cc/9FQh2Yn4/image5.png">

* 1. -log 는 (x = 0 에서 infinite), (x = 1에서 0) 이야
* 2. 실제값이 0 일 때, 예측값이 0일 경우에는 -log값이 무한이어도 (곱했을 때 결과가 0) 이지만
* 3. 실제값이 1일 때, 예측값이 0이면 -log값이 무한이면 (곱했을 때 결과도 무한)으로 나타남.
* 4. 즉, 실제값과 다를 경우, 미친 듯이 값이 error가 치솟는 거죠.

<img width  = 100% src = "https://i.postimg.cc/43CqY6BQ/image7.png">

* 1. 그렇게 구한 error값들을 모아 평균을 내면 우리가 평소에 구했던 Cost function 이 나옵니다.

<img width  = 100% src = "https://i.postimg.cc/0j3ZLv40/image8.png">

* 1. 그리고 그렇게 구한 Cost funtion, 즉 loss값을 미분하면
* 2. Gradient Descent값을 구할 수 있고
* 3. 그렇게 구한 Gradient Descent값으로 weight값을 수정합니다.
* 4. 그리고 개선된 weight값으로 다시 Cost를 구하는 것
* 5. 그게 우리가 아는 함수의 진행 과정입니다.

<img width  = 100% src = "https://i.postimg.cc/rw5gYvN5/image9.png">

* 실제 값을 가지고 진행해볼까요?
* 우리는 세 집단의 Y값을 가지고 분류 과정을 진행하네요

In [3]:
x_data = [
    [1, 2, 1, 1],
    [2, 1, 3, 2],
    [3, 1, 3, 4],
    [4, 1, 5, 5],
    [1, 7, 5, 5],
    [1, 2, 5, 6],
    [1, 6, 6, 6],
    [1, 7, 7, 7]
]

y_data = [
    [0, 0, 1],
    [0, 0, 1],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0],
    [1, 0, 0],
    [1, 0, 0]
]

In [4]:
x_data

[[1, 2, 1, 1],
 [2, 1, 3, 2],
 [3, 1, 3, 4],
 [4, 1, 5, 5],
 [1, 7, 5, 5],
 [1, 2, 5, 6],
 [1, 6, 6, 6],
 [1, 7, 7, 7]]

* X값은 4차원 형태고, Y값은 3종류로 분류됨
* 위 데이터 값은 지금 int(정수)일 테니, float(실수)로 한 번에 바꿔주자
* 이렇게 하면 예전처럼 숫자에 매번 .을 붙이지 않아도 된다.

In [5]:
x_data = np.asarray(x_data, dtype = np.float32)
y_data = np.asarray(y_data, dtype = np.float32)

In [6]:
x_data

array([[1., 2., 1., 1.],
       [2., 1., 3., 2.],
       [3., 1., 3., 4.],
       [4., 1., 5., 5.],
       [1., 7., 5., 5.],
       [1., 2., 5., 6.],
       [1., 6., 6., 6.],
       [1., 7., 7., 7.]], dtype=float32)

In [7]:
nb_classes = 3 # 클래스의 개수 설정 // 3개로 분류한다는 것

In [8]:
print(x_data.shape)
print(y_data.shape)

(8, 4)
(8, 3)


In [9]:
# Weight와 bias를 셋팅하자
W = tf.Variable(tf.random.normal((4, nb_classes)), name = 'weight') # 열 위치는 각 column의 정렬이기에 nb_classes 넣기
b = tf.Variable(tf.random.normal((nb_classes,)), name = 'bias')

* W와 b를 variable이라는 그릇에 담기

In [10]:
variables = [W, b]

In [11]:
print(W)

<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.16052227, -1.6597689 , -1.232133  ],
       [ 0.5971658 ,  1.0609883 , -1.3277572 ],
       [-0.27911443, -0.02141875, -1.502249  ],
       [ 0.3066489 ,  0.5355358 , -1.3167298 ]], dtype=float32)>


In [12]:
print(b)

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([ 0.64973587,  0.32791495, -0.7519815 ], dtype=float32)>


* hypothesis 함수 만들기

<img width="500" src="https://t1.daumcdn.net/cfile/tistory/9959FF345AAD52DF03">

* 1. X * W 를 통해 score를 구함 = (2.0, 1.0, 0.1)
* 2. softmax를 통과시켜 전체 비율 중 해당 결과값이 확률(0.7, 0.2, 0.1)을 만들어줌

In [13]:
# softmax = exp(logits) / reduce_sum(exp(logits), dim)

def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

In [14]:
print(hypothesis(x_data))

tf.Tensor(
[[6.7430651e-01 3.2564253e-01 5.0943025e-05]
 [9.0616632e-01 9.3831733e-02 1.9914553e-06]
 [9.7417474e-01 2.5825273e-02 2.0688438e-08]
 [9.9104238e-01 8.9576421e-03 8.9317338e-11]
 [2.8262276e-02 9.7173780e-01 1.6018376e-15]
 [1.9041234e-01 8.0958766e-01 3.2210564e-11]
 [2.7643861e-02 9.7235614e-01 6.2340206e-16]
 [1.0871028e-02 9.8912901e-01 2.0760157e-18]], shape=(8, 3), dtype=float32)


In [15]:
# Softmax에 대한 원핫인코딩을 테스트해보자

sample_db = [
    [8, 2, 1, 4]
]
sample_db = np.asarray(sample_db, dtype = np.float32)

In [16]:
# 보면 '9.9999714e-01' 는 9.999 * 10^-1 이니까 0.999 . 사실상 1이다. 
print(hypothesis(sample_db))

tf.Tensor([[9.9999714e-01 2.8073625e-06 3.3837280e-11]], shape=(1, 3), dtype=float32)


<img width  = 100% src = "https://i.postimg.cc/9FQh2Yn4/image5.png">

<img width  = 100% src = "https://i.postimg.cc/DyXc8tDR/ch6-2.png">

In [17]:
def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_mean(tf.reduce_sum(Y * tf.math.log(logits), axis =1)) # axis = 차원의 종류의 개수    
# 예시 코드는 cost, cost_mean으로 나누면서 tf.reduce_mean을 붙이는 거를 나눴는데
# 아마 한 번에 이해하기 힘들 수 있어서 그렇게 나눈 듯
    return cost

print(cost_fn(x_data, y_data))

tf.Tensor(6.721287, shape=(), dtype=float32)


<img width  = 100% src = "https://i.postimg.cc/rw5gYvN5/image9.png">

In [18]:
def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y)
        grads = tape.gradient(loss, variables) # loss 함수를 variables로 미분한 값
        
        return grads

In [19]:
print(grad_fn(x_data, y_data))

[<tf.Tensor: id=110, shape=(4, 3), dtype=float32, numpy=
array([[ 0.95381534, -0.2038221 , -0.74999315],
       [-0.9949229 ,  1.49491   , -0.49998704],
       [-0.04926568,  0.9242586 , -0.87499285],
       [-0.01696306,  0.8919562 , -0.87499315]], dtype=float32)>, <tf.Tensor: id=108, shape=(3,), dtype=float32, numpy=array([ 0.22535992,  0.14963347, -0.37499338], dtype=float32)>]


* optimizer를 통해 최적의 Cost값을 찾자

In [20]:
def fit(X, Y, epochs = 2000, verbose = 100):
    optimizer = tf.keras.optimizers.SGD(learning_rate = 0.1) #SGD = 확률적 경사하강법
    
    for i in range(epochs): # 2000번의 epochs를 돌린다.
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i == 0) | ((i +1) % verbose ==0): #만약 i가 0, 혹은 verbose로 나눴을때 0이면
            print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))

* 여기에 우리의 예시 값들을 넣어주면...

In [21]:
fit(x_data, y_data)

Loss at epoch 1: 5.983233
Loss at epoch 100: 0.694579
Loss at epoch 200: 0.593458
Loss at epoch 300: 0.533314
Loss at epoch 400: 0.486159
Loss at epoch 500: 0.445092
Loss at epoch 600: 0.407329
Loss at epoch 700: 0.371230
Loss at epoch 800: 0.335553
Loss at epoch 900: 0.299358
Loss at epoch 1000: 0.263271
Loss at epoch 1100: 0.239523
Loss at epoch 1200: 0.227540
Loss at epoch 1300: 0.216757
Loss at epoch 1400: 0.206913
Loss at epoch 1500: 0.197890
Loss at epoch 1600: 0.189591
Loss at epoch 1700: 0.181932
Loss at epoch 1800: 0.174844
Loss at epoch 1900: 0.168267
Loss at epoch 2000: 0.162148


## Prediction 테스트

* sample data를 넣어서 지금의 모델을 체크해보자
* sample_data = [2, 1, 3, 2] 넣어보자

In [22]:
sample_data = [[2, 1, 3, 2]] # 이 값은 우리가 x_data에서 가지고 있던 2번째 값, label 값은 [0, 0, 1] 이다.

In [23]:
sample_data = np.asarray(sample_data, dtype = np.float32) # 실수로 변환

In [24]:
a = hypothesis(sample_data) # sample_data를 넣은 hypothesis, 즉 예측값

In [25]:
print(a)
print(tf.argmax(a, 1)) # index: 2

tf.Tensor([[0.00149287 0.08491352 0.9135936 ]], shape=(1, 3), dtype=float32)
tf.Tensor([2], shape=(1,), dtype=int64)


## Class로 정리하자면...

In [26]:
class softmax_classifer(tf.keras.Model):
    def __init__(self, nb_classes):
        super(softmax_classifer, self).__init__()
        self.W = tf.Variable(tf.random.normal((4, nb_classes)), name='weight')
        self.b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
        
    def softmax_regression(self, X):
        return tf.nn.softmax(tf.matmul(X, self.W) + self.b)
    
    def cost_fn(self, X, Y):
        logits = self.softmax_regression(X)
        cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(logits), axis=1))        
        return cost
    
    def grad_fn(self, X, Y):
        with tf.GradientTape() as tape:
            cost = self.cost_fn(x_data, y_data)
            grads = tape.gradient(cost, self.variables)            
            return grads
    
    def fit(self, X, Y, epochs=2000, verbose=500):
        optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)

        for i in range(epochs):
            grads = self.grad_fn(X, Y)
            optimizer.apply_gradients(zip(grads, self.variables))
            if (i==0) | ((i+1)%verbose==0):
                print('Loss at epoch %d: %f' %(i+1, self.cost_fn(X, Y).numpy()))
            
model = softmax_classifer(nb_classes)
model.fit(x_data, y_data)

Loss at epoch 1: 7.850834
Loss at epoch 500: 0.523784
Loss at epoch 1000: 0.296680
Loss at epoch 1500: 0.208247
Loss at epoch 2000: 0.169967
